# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='乘车人数')),
                ('aplace', models.CharField(max_length=100, verbose_name='出发地')),
                ('bplace', models.CharField(max_length=100, verbose_name='目的地')),
                ('start', models.DateTimeField(verbose_name='出发时间')),
                ('ab_end', models.DateTimeField(verbose_name='预计到达时间')),
                ('reason', models.TextField(verbose_name='用车原由')),
                ('end', models.DateTimeField(verbose_name='到达时间')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=8, verbose_name='车牌号')),
                ('brand', models.CharField(max_length=10, verbose_name='品牌')),
                ('style', models.CharField(max_length=10, verbose_name='类型')),
                ('cap', models.IntegerField(verbose_name='容量')),
                ('state', models.SmallIntegerField(default=1, verbose_name='0报废、1在岗、2忙碌')),
            ],
        ),
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecar.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att1', models.SmallIntegerField(null=True, verbose_name='0不同意、1同意')),
                ('att2', models.SmallIntegerField(null=True, verbose_name='0不同意、1同意')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('tel', models.CharField(max_length=14, verbose_name='手机号')),
                ('role', models.SmallIntegerField(default=3, verbose_name='1司机、2调度人、3申请人、45审核人')),
                ('state', models.SmallIntegerField(default=1, verbose_name='0离职、1在岗、2忙碌')),
                ('co', models.ManyToManyField(to='usecar.Companies')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam1_examset', to='usecar.Persons'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam2_examset', to='usecar.Persons'),
        ),
        migrations.AddField(
            model_name='exam',
            name='num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usecar.Application'),
        ),
        migrations.AddField(
            model_name='cc',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecar.Persons'),
        ),
        migrations.AddField(
            model_name='cars',
            name='co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecar.Companies'),
        ),
        migrations.AddField(
            model_name='application',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecar.Cars'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecar.Persons'),
        ),
    ]
