# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='state',
            field=models.SmallIntegerField(default=1, verbose_name='车辆状态（0报废、1在岗、2忙碌）'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=200, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='att1',
            field=models.SmallIntegerField(null=True, verbose_name='审核人1意见（0不同意、1同意）'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='att2',
            field=models.SmallIntegerField(null=True, verbose_name='审核人2意见（0不同意、1同意）'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='role',
            field=models.SmallIntegerField(default=3, verbose_name='角色：（1司机、2调度人、3申请人、45审核人）'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='state',
            field=models.SmallIntegerField(default=1, verbose_name='状态：（0离职、1在岗、2忙碌）'),
        ),
    ]
