# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0002_auto_20170714_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=20, verbose_name='单位名称'),
        ),
    ]
