# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0003_auto_20170715_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usecar.Cars'),
        ),
        migrations.AlterField(
            model_name='application',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='\u5230\u8fbe\u65f6\u95f4'),
        ),
    ]
