# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0004_auto_20170721_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usecar.Cars'),
        ),
        migrations.AlterField(
            model_name='application',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5230\u8fbe\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='att1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u5ba1\u6838\u4eba1\u610f\u89c1\uff080\u4e0d\u540c\u610f\u30011\u540c\u610f\uff09'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='att2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u5ba1\u6838\u4eba2\u610f\u89c1\uff080\u4e0d\u540c\u610f\u30011\u540c\u610f\uff09'),
        ),
    ]
