# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0005_auto_20170722_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_set', to='usecar.Persons'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_set', to='usecar.Persons'),
        ),
    ]
