# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecar', '0008_auto_20170723_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ab_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u9884\u8ba1\u7528\u65f6'),
        ),
    ]
